### PR TITLE
Ignore pam_unix_non_existent on getpwnam calls

### LINKED ISSUE #468: Running `sudo` causes authd to log "WARN rpc error: code = NotFound desc ="
### Describe the issue

authd prints unhelpful warning messages to the journal when `sudo` is executed.

### Where does the issue happens

- [ ] I can reproduce the issue in the graphical display manager
- [ ] I can reproduce the issue on a terminal with "login"

### Steps to reproduce it

1. Ensure that `authd` and `authd-msentraid` are running
2. Follow the output of `authd`:
   ```
   sudo journalctl -u authd.service -f
   ```
3. Run any command via `sudo` in another terminal:
   ```
   sudo ls
   ```
4. Observe how `authd` logs `WARN rpc error: code = NotFound desc =`

### PR DESCRIPTION
**Pull request by denisonbarbosa**
This is a common call done by PAM to prevent attacks. We need to special case it to avoid spamming the system logs with Not Found messages when the call happens.

Closes #468.
UDENG-3934

### CODE REVIEW

File: nss/src/passwd/mod.rs [hunk 1]
```diff
@@ -108,6 +108,12 @@ fn get_entry_by_name(name: String) -> Response<Passwd> {
             }
         };
 
+        // This is a fake call done by PAM to avoid attacks, so we need to special case it to avoid spamming
+        // logs with "Not Found" messages, as this call is done quite frequently.
+        if name.contains("pam_unix_non_existent") {
```
Comment (3v1n0) [inline nss/src/passwd/mod.rs:113]: You can probably just use:

```suggestion
        if name == "pam_unix_non_existent" {
```

And maybe reference the code doing it: https://github.com/linux-pam/linux-pam/blob/8401cef10cd5f62849c5fcfef4c82db92712296c/modules/pam_unix/support.c#L700

Comment (denisonbarbosa) [reply nss/src/passwd/mod.rs:113]: Yeah, I thought about using direct comparison, but then wasn't sure whether there could be other formats used by PAM to achieve the same thing. Overall, I think it's safe to keep it as  `.contains()` rather than a direct comparison. Do you think there could be any issues?

**Review by didrocks — APPROVED** [review]
Thanks for adding the test!

File: nss/src/passwd/mod.rs (hunk 1 above)
Comment (3v1n0) [reply nss/src/passwd/mod.rs:113]: No, not an issue... I don't think that code will ever change TBH, and in this kind of things the more restrict we are, the best.

But it's not a strong opinion.

Comment (3v1n0) [reply nss/src/passwd/mod.rs]: Nice!

**Review by 3v1n0 — APPROVED** [review]
