### PR TITLE
pam/adapter: fix authTracker race with a generation counter

### LINKED ISSUE #1424: GDM login sometimes broken after successful device auth (no password entry)
The e2e-tests sometimes fail after successful device auth. The QR code is hidden but the "Create a local password" entry is not shown:

Image

Runs where that happened:
* https://authd-e2e-test-logs.adrian-dombeck.workers.dev/pr-1412/run-24181569519-1/questing-authd-google/log.html#s1-s8
* https://authd-e2e-test-logs.adrian-dombeck.workers.dev/pr-1412/run-24285589862-1/devel-authd-google/log.html#s1-s8-t1

Relevant logs from [this run](https://authd-e2e-test-logs.adrian-dombeck.workers.dev/pr-1412/run-24181569519-1/questing-authd-google/log.html#s1-s8) ([full journal](https://authd-e2e-test-logs.adrian-dombeck.workers.dev/pr-1412/run-24181569519-1/questing-authd-google/log.html#s1-s8-t1-k8-k3)):

```
Apr 09 09:15:23 ubuntu authd-google[2350]: Exchanged device code for token.
Apr 09 09:15:23 ubuntu authd-google[2350]: IsAuthenticated result (session ab35ba60-a217-4342-bcce-a1d9c53215cf): next, {}
Apr 09 09:15:23 ubuntu authd[1013]: 3820511142-ab35ba60-a217-4342-bcce-a1d9c53215cf: Authentication result: next
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Authentication completed for session "3820511142-ab35ba60-a217-4342-bcce-a1d9c53215cf": adapter.isAuthenticatedResultReceived{access:"next", secret:(*string)(nil), msg:"{}"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.isAuthenticatedResultReceived{access:"next", secret:(*string)(nil), msg:"{}"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.isAuthenticatedRequestedSend{adapter.isAuthenticatedRequested{*authd.IARequest_AuthenticationData_Wait{Wait:"true"}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Sending to GDM: {"type":"event","event":{"type":"authEvent","authEvent":{"response":{"access":"next"}}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Authentication request for session "3820511142-ab35ba60-a217-4342-bcce-a1d9c53215cf": &authd.IARequest_AuthenticationData_Wait{Wait:"true"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.GetAuthenticationModesRequested{}
Apr 09 09:15:23 ubuntu authd-google[2350]: Handling IsAuthenticated call for session ab35ba60-a217-4342-bcce-a1d9c53215cf
Apr 09 09:15:23 ubuntu authd-google[2350]: Device code expiry time: 2026-04-09 09:44:14.865466026 +0000 UTC
Apr 09 09:15:23 ubuntu authd-google[2350]: Polling to exchange device code for token...
Apr 09 09:15:23 ubuntu authd-google[2350]: Getting authentication modes for session ab35ba60-a217-4342-bcce-a1d9c53215cf
Apr 09 09:15:23 ubuntu authd-google[2350]: Got authentication modes for session ab35ba60-a217-4342-bcce-a1d9c53215cf: [map[id:newpassword label:Define your local password]]
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: authModes[id:"newpassword" label:"Define your local password"]
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.authModesReceived{authModes:[]*authd.GAMResponse_AuthenticationMode{(*authd.GAMResponse_AuthenticationMode)(0xc0002a4ff0)}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.ChangeStage{Stage:"authModeSelection"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: *adapter.authenticationModel: Blur
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: *adapter.focusTrackerModel: Blur
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: *adapter.authenticationModel: Reset
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.List: Focus
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Sending to GDM: {"type":"event","event":{"type":"authModesReceived","authModesReceived":{"authModes":[{"id":"newpassword","label":"Define your local password"}]}}}
Apr 09 09:15:23 ubuntu gnome-shell[1591]: authd: Access response: next
Apr 09 09:15:23 ubuntu authd[1013]: Authentication aborted: PAM client disconnected unexpectedly (session ab35ba60-a217-4342-bcce-a1d9c53215cf)
Apr 09 09:15:23 ubuntu authd[1013]: Cancelling broker authentication (session ab35ba60-a217-4342-bcce-a1d9c53215cf)
Apr 09 09:15:23 ubuntu authd-google[2350]: Cancelling IsAuthenticated call for session ab35ba60-a217-4342-bcce-a1d9c53215cf
Apr 09 09:15:23 ubuntu authd-google[2350]: Error retrieving access token: context canceled
Apr 09 09:15:23 ubuntu authd[1013]: 3820511142-ab35ba60-a217-4342-bcce-a1d9c53215cf: Authentication result: cancelled
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"eventAck"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: EventSend&{response:{access:"next"}}result<nil>
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"eventAck"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: EventSend&{authModes:{id:"newpassword" label:"Define your local password"}}result<nil>
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Authentication completed for session "3820511142-ab35ba60-a217-4342-bcce-a1d9c53215cf": adapter.isAuthenticatedResultReceived{access:"cancelled", secret:(*string)(nil), msg:""}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.isAuthenticatedResultReceived{access:"cancelled", secret:(*string)(nil), msg:""}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.stopAuthentication{}, current model <nil>, focused false
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.listFocused{id:0x2}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.listFocused{id:0x2}, autoselect: "newpassword"
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.authModeSelected{id:"newpassword"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Sending to GDM: {"type":"event","event":{"type":"authEvent","authEvent":{"response":{"access":"cancelled"}}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.StageChanged{Stage:"authModeSelection"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.AuthModeSelected{ID:"newpassword"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Sending to GDM: {"type":"request","request":{"type":"changeStage","changeStage":{"stage":"authModeSelection"}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Sending to GDM: {"type":"event","event":{"type":"authModeSelected","authModeSelected":{"authModeId":"newpassword"}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"eventAck"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: EventSend&{response:{access:"cancelled"}}result<nil>
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"response","response":{"type":"changeStage","ack":{}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Gdm stage change to authModeSelection sent
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"eventAck"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: EventSend&{authModeId:"newpassword"}result<nil>
Apr 09 09:15:23 ubuntu authd-google[2350]: Selecting authentication mode newpassword for session ab35ba60-a217-4342-bcce-a1d9c53215cf
Apr 09 09:15:23 ubuntu authd-google[2350]: Selected authentication mode newpassword for session ab35ba60-a217-4342-bcce-a1d9c53215cf: map[entry:chars_password label:Create a local password type:newpassword]
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"pollResponse","pollResponse":[{"type":"authModeSelected","authModeSelected":{"authModeId":"newpassword"}}]}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: GDM poll response: type:authModeSelected authModeSelected:{authModeId:"newpassword"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.authModeSelected{id:"newpassword"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.AuthModeSelected{ID:"newpassword"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Sending to GDM: {"type":"event","event":{"type":"authModeSelected","authModeSelected":{"authModeId":"newpassword"}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.UILayoutReceived{&authd.UILayout{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(nil)}, Type:"newpassword", Label:(*string)(0xc000312740), Button:(*string)(0xc0003127d0), Wait:(*string)(0xc0003127e0), Entry:(*string)(0xc000312890), Content:(*string)(0xc0003129f0), Code:(*string)(0xc000312a00), RendersQrcode:(*bool)(nil), unknownFields:[]uint8(nil), sizeCache:0}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Sending to GDM: {"type":"event","event":{"type":"uiLayoutReceived","uiLayoutReceived":{"uiLayout":{"type":"newpassword","label":"Create a local password","button":"","wait":"","entry":"chars_password","content":"","code":""}}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"eventAck"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: EventSend&{authModeId:"newpassword"}result<nil>
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"eventAck"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: EventSend&{uiLayout:{type:"newpassword" label:"Create a local password" button:"" wait:"" entry:"chars_password" content:"" code:""}}result<nil>
Apr 09 09:15:23 ubuntu authd-google[2350]: Selecting authentication mode newpassword for session ab35ba60-a217-4342-bcce-a1d9c53215cf
Apr 09 09:15:23 ubuntu authd-google[2350]: Selected authentication mode newpassword for session ab35ba60-a217-4342-bcce-a1d9c53215cf: map[entry:chars_password label:Create a local password type:newpassword]
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.ChangeStage{Stage:"challenge"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: *adapter.List: Blur
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.authenticationModel: Focus, focused false
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: *adapter.focusTrackerModel: Focus
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.UILayoutReceived{&authd.UILayout{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(nil)}, Type:"newpassword", Label:(*string)(0xc000312df0), Button:(*string)(0xc000312e00), Wait:(*string)(0xc000312e10), Entry:(*string)(0xc000312e20), Content:(*string)(0xc000312e30), Code:(*string)(0xc000312e40), RendersQrcode:(*bool)(nil), unknownFields:[]uint8(nil), sizeCache:0}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Sending to GDM: {"type":"event","event":{"type":"uiLayoutReceived","uiLayoutReceived":{"uiLayout":{"type":"newpassword","label":"Create a local password","button":"","wait":"","entry":"chars_password","content":"","code":""}}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"eventAck"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: EventSend&{uiLayout:{type:"newpassword" label:"Create a local password" button:"" wait:"" entry:"chars_password" content:"" code:""}}result<nil>
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.StageChanged{Stage:"challenge"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.StageChanged{Stage:"challenge"}, in progress false, focused: false
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Sending to GDM: {"type":"request","request":{"type":"changeStage","changeStage":{"stage":"challenge"}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.ChangeStage{Stage:"challenge"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.authenticationModel: Focus, focused false
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: *adapter.focusTrackerModel: Focus
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.StageChanged{Stage:"challenge"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.StageChanged{Stage:"challenge"}, in progress false, focused: true
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Sending to GDM: {"type":"request","request":{"type":"changeStage","changeStage":{"stage":"challenge"}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: adapter.startAuthentication{}, current model &{true}, focused true
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Sending to GDM: {"type":"event","event":{"type":"startAuthentication","startAuthentication":{}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"response","response":{"type":"changeStage","ack":{}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Gdm stage change to challenge sent
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"response","response":{"type":"changeStage","ack":{}}}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Gdm stage change to challenge sent
Apr 09 09:15:23 ubuntu gnome-shell[1591]: authd: Starting challenge request newpassword Create a local password
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: Got from GDM: {"type":"eventAck"}
Apr 09 09:15:23 ubuntu gdm-session-wor[2336]: EventSend&{}result<nil>
Apr 09 09:17:01 ubuntu authd-pam[2458]: failed to call com.ubuntu.authd.pam.GetData: No module specific data is present
Apr 09 09:17:01 ubuntu authd-pam[2458]: AcctMgmt: exiting with error The return value should be ignored by PAM dispatch
```

### PR DESCRIPTION
**Pull request by adombeck**
The authTracker coordinates `IsAuthenticated` RPC calls: at most one goroutine may be in flight at a time, and `cancelAndWait()` must both cancel the in-flight RPC and prevent any queued goroutine from starting a new one.

The previous implementation used a `sync.Cond` and a `cancelFunc` pointer. `cancelAndWait()` read `cancelFunc` under the lock, then released the lock before calling it. This left a window where:

1. An auth result arrives; `reset()` clears `cancelFunc` and signals the `cond` (unlocking any goroutine waiting in `waitAndStart`).
2. That goroutine sets a new `cancelFunc` and starts the next RPC.
3. `cancelAndWait()` (from the `Reset()` command that fires as part of the stage transition triggered by the auth result) then arrives, reads `cancelFunc=nil`, and returns without doing anything -- but the new RPC is already in flight and will be wrongly cancelled later.

Replace the implementation with a generation counter:

* `cancelAndWait()` atomically bumps the generation counter and snapshots `cancelFunc` + `done`, all under the mutex.
* `waitForSlot()` captures the generation before blocking. After it is woken by a finished peer, it re-checks the generation under the lock. If it has changed, `cancelAndWait()` was called in the interim, and the goroutine aborts without making the RPC.

Because the generation bump and the snapshot of `done` happen under the same mutex as `waitForSlot`'s generation check, there is no window between “woken” and “checked”: if `cancelAndWait()` ran at any point before or during the wait, the generation will be stale.

The `sync.Cond` is replaced by a plain `sync.Mutex` and a per-auth `done` channel (created in `waitForSlot`, closed in `finish`), which `cancelAndWait()` waits on to confirm the old goroutine has exited.

Closes #1424

### CODE REVIEW

**Comment by adombeck** [comment]
This was created by Copilot when I asked it to debug #1424. It sounds plausible to me but I'll request a review from @3v1n0 if/once the tests pass.

**Comment by 3v1n0** [comment]
> This was created by Copilot when I asked it to debug #1424. It sounds plausible to me but I'll request a review from @3v1n0 if/once the tests pass.

Not sure, this seems to increase the complexity even more. 

And last time I spent time on this, the problems were really in the service side, due to how we send cancelation back, as per an API problem we have (to add to the list?) of not being able to catch a cancelled event

**Comment by 3v1n0** [comment]
I mean see https://github.com/canonical/authd/commit/79e5f47202aa9c184a4ec4815d48c387e4eee639 (sadly the original log got lost), while the initial version of it was in the server side via https://github.com/canonical/authd/commit/2d7ea65a54b715dace841ae9bf9595f9d2949c36

At the time Didier preferred to keep the change in the client, since we were aiming too do a v2 of the proto, but at this point...

**Comment by adombeck** [comment]
I added a new commit (also created by copilot) which handles the problem on the server side. However, to me the issue described here:

> The previous implementation used a `sync.Cond` and a `cancelFunc` pointer. `cancelAndWait()` read `cancelFunc` under the lock, then released the lock before calling it. This left a window where:
> 
> 1. An auth result arrives; `reset()` clears `cancelFunc` and signals the `cond` (unlocking any goroutine waiting in `waitAndStart`).
> 2. That goroutine sets a new `cancelFunc` and starts the next RPC.
> 3. `cancelAndWait()` (from the `Reset()` command that fires as part of the stage transition triggered by the auth result) then arrives, reads `cancelFunc=nil`, and returns without doing anything -- but the new RPC is already in flight and will be wrongly cancelled later.

still seems like a valid, orthogonal issue, no? So I would keep the other commit as well.

File: pam/internal/adapter/authentication.go [hunk 1]
```diff
@@ -293,7 +302,12 @@ func (m authenticationModel) Update(msg tea.Msg) (authModel authenticationModel,
 		clientType := m.clientType
 		currentLayout := m.currentLayout
 		return m, func() tea.Msg {
-			authTracker.waitAndStart(cancelFunc)
+			// waitForSlot blocks until no other auth is in flight, then registers
+			// us as the active goroutine for this generation.  It returns false
+			// if we have been superseded by a cancelAndWait() call and must abort.
+			if !authTracker.waitForSlot(cancelFunc) {
+				return nil
+			}
```
Comment (denisonbarbosa) [inline pam/internal/adapter/authentication.go:310]: What sucks here is that the user trying to authenticate might have to end up waiting for some minutes (yes, narrow use case and only likely to happen with SSH), but still would be nice to be able to at least let the user know 🥲

Comment (adombeck) [reply pam/internal/adapter/authentication.go:310]: when would that happen? we're only tracking authentication requests created by the current process, so multiple SSH connections in parallel do not block each other. in the same SSH connection, the only way I see for multiple authentications to happen is if the broker returns `auth.Retry` or `auth.Next`, both of which are only sent when the previous authentication attempt has finished.

File: internal/brokers/testdata/golden/TestIsAuthenticated/Successfully_authenticate_after_second_call_without_cancelling [hunk 2]
```diff
@@ -3,6 +3,6 @@ FIRST CALL:
 	data: {"Name":"ia_second_call@example.com","UID":0,"Gecos":"gecos for ia_second_call@example.com","Dir":"/home/ia_second_call@example.com","Shell":"/bin/sh/ia_second_call@example.com","Groups":[{"Name":"group-ia_second_call@example.com","GID":null,"UGID":"ugid-ia_second_call@example.com"}]}
 	err: <nil>
 SECOND CALL:
-	access: 
-	data: 
-	err: broker "TestIsAuthenticated": IsAuthenticated already running for session "TestIsAuthenticated/Error_when_calling_IsAuthenticated_a_second_time_without_cancelling_separator_ia_second_call"
+	access: granted
+	data: {"Name":"ia_second_call@example.com","UID":0,"Gecos":"gecos for ia_second_call@example.com","Dir":"/home/ia_second_call@example.com","Shell":"/bin/sh/ia_second_call@example.com","Groups":[{"Name":"group-ia_second_call@example.com","GID":null,"UGID":"ugid-ia_second_call@example.com"}]}
+	err: <nil>
```
Comment (denisonbarbosa) [inline internal/brokers/testdata/golden/TestIsAuthenticated/Successfully_authenticate_after_second_call_without_cancelling:8]: It would be useful to know when the mutex guard is reached, but it's not worth the time or complexity to implement this. I guess we can always check the test coverage to see if the expected code path was reached.

**Review by denisonbarbosa — APPROVED** [review]
LGTM!
