### PR TITLE
Use lowercase usernames

### LINKED ISSUE #530: Issue: Authentication failure if Entra username and local username differ in upper and lower case
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

Login fails with "Authentication failure" if e.g. the username in Entra contains uppercase letters but I'm trying to log in with the username in lowercase.

The log shows

```
Sep 12 12:14:33 ubuntu login[215574]: pam_unix(login:account): could not identify user (from getpwnam(Aadtest-testauthd@uaadtest.onmicrosoft.com))
Sep 12 12:14:33 ubuntu login[215574]: Authentication failure
```

### Steps to reproduce

1. Log in with a username which differs in upper- or lowercase from the username in Entra. For example, let's say the username in Entra is `Foo@Bar.onmicrosoft.com` and you try to log in with: 
   ```
   sudo login foo@bar.onmicrosoft.com
   ```
2. Complete the device authentication
3. Set a password
4. Observe that login fails with `Authentication failure`

#### authd version
```
authd	0.3.4~ppa3
```

#### authd-msentraid broker version
```
name:      authd-msentraid
summary:   MS EntraID Broker for authd
publisher: --
store-url: https://snapcraft.io/authd-msentraid
license:   GPL-3.0
description: |
  Broker that enables OIDC authentication with MS EntraID group management
  for authd.
services:
  authd-msentraid: simple, enabled, active
refresh-date: today at 12:03 CEST
channels:
  0.x/stable:    0.1           2024-08-23 (33) 17MB -
  0.x/candidate: ^                                  
  0.x/beta:      ^                                  
  0.x/edge:      0.1           2024-09-10 (44) 17MB -
installed:       main~2182c5f4            (x1) 17MB -
```

#### gnome-shell version
```
gnome-shell:
  Installed: 46.3.1-1ubuntu1~24.04.1authd1
  Candidate: 46.3.1-1ubuntu1~24.04.1authd1
  Version table:
 *** 46.3.1-1ubuntu1~24.04.1authd1 500
        500 https://ppa.launchpadcontent.net/ubuntu-enterprise-desktop/authd-edge/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status
     46.3.1-1ubuntu1~24.04.1 500
        500 https://ppa.launchpadcontent.net/ubuntu-enterprise-desktop/authd/ubuntu noble/main amd64 Packages
     46.0-0ubuntu6~24.04.4 500
        500 http://de.archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages
     46.0-0ubuntu6~24.04.3 500
        500 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages
     46.0-0ubuntu5 500
        500 http://de.archive.ubuntu.com/ubuntu noble/main amd64 Packages
```

#### Distribution
```
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

#### Logs
```
[666773.117338] ubuntu authd[215459]: DEBUG User "<username in lowercase>" is unknown
[666794.091449] ubuntu authd[215459]: 2024/09/12 12:14:33 WARN rpc error: code = NotFound desc =
[666794.095322] ubuntu authd[215459]: 2024/09/12 12:14:33 WARN rpc error: code = NotFound desc =
[666794.095322] ubuntu authd[215459]: 2024/09/12 12:14:33 WARN rpc error: code = NotFound desc =
```

#### /etc/authd/brokers.d/authd-msentraid.conf
```
[authd]
name = Microsoft Entra ID
brand_icon = /snap/authd-msentraid/current/broker_icon.png
dbus_name = com.ubuntu.authd.MSEntraID
dbus_object = /com/ubuntu/authd/MSEntraID

```

#### authd-msentraid configuration
```
[oidc]
issuer = https://login.microsoftonline.com/<UUID redacted>/v2.0
client_id = <UUID redacted> 
#client_id = <UUID redacted>
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

### PR DESCRIPTION
**Pull request by adombeck**
All the brokers we currently support (msentraid and google) use case-insensitive usernames. Currently, logging in with a username which differs in upper- or lowercase from the username in the broker results in an authentication failure. We want to fix that. 

The easiest way to do that is to convert all usernames to lowercase before storing them in our database or passing them to the broker, and also convert the Name argument of GetPassdByName to lowercase before querying the database. 

If we (or anyone else) ever wants to add a broker for a provider which does *not* use case-insensitive usernames, we will have to revisit this and decide whether we want to support that.

Review and merge together with https://github.com/ubuntu/authd-oidc-brokers/pull/314

Closes #530, #531 
UDENG-4518
UDENG-4519
UDENG-6636
UDENG-6822

### CODE REVIEW

**Review by 3v1n0 — COMMENTED** [review]
So... There are some improvements to do in the code (mostly the handling of the passwd file is my main concern).

However, in general I'm not fully sure that this is the right path to take if we want to be consistent with the authd architecture and we want to be future proof, I mean:
 - Authd is meant to be brokers-agnostic, the fact we've two brokers handling with domain-like names right now, it doesn't imply that we may support very different other kinds in future that instead require having case-sensitive names.
 - Unix usernames are case-insensitive? authd user names should folllow it.
 - It should be the up to the brokers work to do the username sanitizing and telling authd if two usernames match

So, this said... I'm still thinking that we should take the path of adding further method(s)? to the brokers (and maybe NSS) API in order to achieve something like this without touching authd "core" too much.

If we want to do some kind of migration, maybe brokers can provide features "flags" telling us how to behave, or we can make them do some user-matching check...

**Comment by adombeck** [comment]
> Authd is meant to be brokers-agnostic, the fact we've two brokers handling with domain-like names right now, it doesn't imply that we may support very different other kinds in future that instead require having case-sensitive names.

We had that discussion on [the Jira ticket](https://warthogs.atlassian.net/browse/UDENG-4518):
> [I wonder] whether we can assume that all brokers we want to support use case-insensitive usernames. It’s true for now and we could go the easy route until we have a case where we (or someone else) wants to add a broker that uses case-insensitive usernames and then decide whether it’s worth the effort to support that.

Didier agreed with that approach, so I implemented it.

> It should be the up to the brokers work to do the username sanitizing and telling authd if two usernames match

We still have the  `VerifyUsername` method in the broker implementations, which can do some extra checks: https://github.com/ubuntu/authd-oidc-brokers/blob/29fbea02672f26264825bea5b815e8fe265f8be3/internal/providers/msentraid/msentraid.go#L318-L318

File: internal/users/cache/migration.go [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+	}
+
+	// Rename the user in /etc/group
+	// Note that we can't use gpasswd here because it checks for the existence of the user, which causes an NSS request
+	// being sent to authd, but authd is not ready yet because we are still migrating the database.
+	content, err := os.ReadFile("/etc/group")
+	if err != nil {
+		return fmt.Errorf("error reading /etc/group: %w", err)
+	}
+	content = bytes.ReplaceAll(content, []byte(oldName), []byte(newName))
```
[the remark this answers is not in the document]
Comment (adombeck) [reply internal/users/cache/migration.go:155]: You're right, the full text search and replace is indeed dangerous. We could parse each line instead, by splitting on `:` and `,`, which I assume is what tools like `gpasswd` also do.

We might also be able to avoid using `/etc/group` altogether by using `SUCCESS=merge` for groups in `/etc/nsswitch.conf` and storing the groups in our database instead (I tracked that [here](https://warthogs.atlassian.net/browse/UDENG-5791)).

**Comment by adombeck** [comment]
Converting to draft because of https://warthogs.atlassian.net/browse/UDENG-5830

File: internal/users/cache/db_test.go [hunk 2]
```diff
@@ -136,6 +136,15 @@ func TestUpdateUserEntry(t *testing.T) {
 			// These values don't matter. We just want to make sure they are the same as the ones provided by the manager.
 			LastPwdChange: -1, MaxPwdAge: -1, PwdWarnPeriod: -1, PwdInactivity: -1, MinPwdAge: -1, ExpirationDate: -1,
 		},
+		"user1-in-caps": {
+			Name:  "User1",
```
[the remark this answers is not in the document]
Comment (adombeck) [reply internal/users/cache/db_test.go]: I fixed the test name

File: internal/consts/consts.go
[the remark this answers is not in the document]
Comment (adombeck) [reply internal/consts/consts.go:1]: GitHub doesn't show the lines this was referring to anymore :/

File: internal/users/cache/migration.go [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+	}
+
+	// If the version is less than 0.3.8-pre1, we need to migrate lowercase usernames.
+	// Use semantic versioning to compare versions.
+	if version == "" || semver.Compare(version, initialLowercaseUsernamesVersion) < 0 {
+		log.Infof(context.Background(), "Migrating database to lowercase usernames (database version: %q)", version)
+		if err := migrateToLowercaseUsernames(c); err != nil {
+			return err
+		}
+	}
```
[the remark this answers is not in the document]
Comment (adombeck) [reply internal/users/cache/migration.go]: obsolete

File: internal/users/cache/migration.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (adombeck) [reply internal/users/cache/migration.go]: > We could parse each line instead, by splitting on `: and `,`

I implemented that

**Comment by 3v1n0** [comment]
Could you please also include integration tests ensuring that things works as expected in PAM and SSH side too by using using using this?

```diff
diff --git a/examplebroker/broker.go b/examplebroker/broker.go
index 42201c6b..be9a06ed 100644
--- a/examplebroker/broker.go
+++ b/examplebroker/broker.go
@@ -337,6 +337,14 @@ func (b *Broker) NewSession(ctx context.Context, username, lang, mode string) (s
 		}
 	}
 
+	if strings.HasPrefix(username, UserIntegrationCaseInsensitivePrefix) {
+		username = strings.ToLower(username)
+		info.username = username
+		if _, ok := exampleUsers[username]; !ok {
+			exampleUsers[username] = userInfoBroker{Password: "goodpass"}
+		}
+	}
+
 	if info.sessionMode == auth.SessionModeChangePassword {
 		info.neededAuthSteps++
 		info.pwdChange = mustReset
@@ -928,6 +936,10 @@ func userInfoFromName(name string) string {
 		UGID string
 	}
 
+	if strings.HasPrefix(name, UserIntegrationCaseInsensitivePrefix) {
+		name = strings.ToLower(name)
+	}
+
 	user := struct {
 		Name   string
 		UUID   string
diff --git a/examplebroker/users.go b/examplebroker/users.go
index 2329cc9f..dba30dfb 100644
--- a/examplebroker/users.go
+++ b/examplebroker/users.go
@@ -50,4 +50,7 @@ const (
 	// UserIntegrationAuthModesPrefix is the prefix for an user listing for supported auth modes.
 	// The modes can be exposed as list, in the form: `user-auth-modes-id1,id2,id3-integration-whatever`.
 	UserIntegrationAuthModesPrefix = "user-auth-modes-"
+	// UserIntegrationCaseInsensitivePrefix is the prefix for users that are case-insensitive.
+	// Note that to simplify the logic only the part after the prefix can be case-insensitive.
+	UserIntegrationCaseInsensitivePrefix = "user-case-insensitive-"
 )
```

It implies that if you login with `user-case-insensitive-FooBar` should also allow logging in with `user-case-insensitive-FOOBAR`

**Comment by adombeck** [comment]
Rebased on main and resolved conflicts

**Comment by adombeck** [comment]
@3v1n0 this PR is the only remaining blocker for doing a stable authd release, which we want to do this pulse. do you think we could do https://github.com/ubuntu/authd/pull/723#issuecomment-2755608565 as a follow-up to unblock the release?

**Comment by 3v1n0** [comment]
> @3v1n0 this PR is the only remaining blocker for doing a stable authd release, which we want to do this pulse. do you think we could do [#723 (comment)](https://github.com/ubuntu/authd/pull/723#issuecomment-2755608565) as a follow-up to unblock the release?

I'll see if I can handle it tomorrow

File: internal/users/db/testdata/golden/TestMigrationToLowercaseUserAndGroupNames/groups [hunk 4]
```diff
@@ -0,0 +1 @@
+Group1:x:11111:user1
```
[the remark this answers is not in the document]
Comment (adombeck) [reply internal/users/db/testdata/golden/TestMigrationToLowercaseUserAndGroupNames/groups:1]: Yes, that's intended. We rename the authd users in the groups file, but I don't think we should rename the local groups, because those were not created by authd. Does that make sense?

File: internal/users/db/migration.go [hunk 5]
```diff
@@ -0,0 +1,252 @@
...
+
+	log.Debugf(context.Background(), "Schema version after migrations: %d", v)
+
+	return nil
+}
+
+// renameUsersInUserGroupFile renames users in the /etc/group file.
+func renameUsersInUserGroupFile(oldNames, newNames []string) error {
+	// Note that we can't use gpasswd here because it checks for the existence of the user, which causes an NSS request
+	// being sent to authd, but authd is not ready yet because we are still migrating the database.
```
Comment (3v1n0) [inline internal/users/db/migration.go:214]: I'm still wondering if  we could try to use it: we are in control of our NSS service, so basically we can just not start it until the migration is ready, and this would prevent the self-call... no?

**Comment by 3v1n0** [comment]
What should be the behavior on groups now? Querying an upper-case user group name should return the actual group in lower case?

**Comment by adombeck** [comment]
> What should be the behavior on groups now? Querying an upper-case user group name should return the actual group in lower case?

Mmh, good question. I see that the behavior of querying users by name and querying groups by name is inconsistent on this PR, in that querying users happens case-insensitively and querying groups does not. There is a an argument in favor of this (i.e. not querying groups case-insensitively): If at some point we want to support a broker which does use case-sentitive group names, we can just change the behavior so that groups are only *stored* in lowercase for those brokers which use case-insensitive group names. However, changing the behavior of group names are *queried* can break apps which query authd groups.

The same is true for user names, but there we have a use case which, IIUC, requires that querying user names happens case-insensitively, which is that users should be able to log in with the same letter case as they use to log in with their identity provider.

Does that make sense?

**Comment by adombeck** [comment]
@3v1n0 Further investigation showed that `gpasswd` does not only use `lckpwdf` (which according to the man page is meant to protect the shadow password database) to protect against multiple simultaneous accesses, but also a lock file `/etc/group.lock`. That lock file is also used by other tools/libraries like libuser (see https://salsa.debian.org/debian/libuser/blob/7abf20577065bf0d48703ece1c0a1b18a4bc2e67/modules/files.c#L291-L291), so I decided to use that instead of `lckpwdf`.

Note that we can't use `gpasswd` after reading `/etc/group` with a lock file, because:
1. We would have to remove the lock file before running `gpasswd`, which again opens a window for simultaneous write accesses.
2. `gpasswd --add` does indeed issue an NSS request, as indicated by my comment in `renameUsersInGroupFile` (I updated that comment to make it clear that it's `gpasswd --add` - `gpasswd --delete` does not issue an NSS request, which is what we tried earlier in our call).

So I'm instead reading and modifying `/etc/group` before releasing the lock.

**Comment by adombeck** [comment]
@3v1n0 There are some minor conflicts in `pam/integration-tests/cli_test.go`. I'm not sure how to resolve those, do you mind doing that?

**Comment by 3v1n0** [comment]
> 2\. `gpasswd --add` does indeed issue an NSS request, as indicated by my comment in `renameUsersInGroupFile` (I updated that comment to make it clear that it's `gpasswd --add` - `gpasswd --delete` does not issue an NSS request, which is what we tried earlier in our call).

Oh I looked to me we used add too... weird we actualy did not!

File: internal/userutils/userutils.go [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+)
+
+var groupFile = "/etc/group"
+
+// LockGroupFile creates a lock file at /etc/group.lock, the same location
+// used by tools like gpasswd and groupmod to prevent concurrent modifications
+// to the /etc/group file.
+// The lock file contains the PID of the process that created it.
+func LockGroupFile() (err error) {
+	lockFile, err := os.OpenFile(groupFile+".lock", os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
```
Comment (3v1n0) [inline internal/userutils/userutils.go:17]: Would be possible to use both locking systems as gpasswd (so also `lckpwdf`)?

File: internal/userutils/userutils_test.go [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+import (
+	"os"
+	"os/exec"
+	"testing"
+
+	"github.com/stretchr/testify/require"
+	"github.com/ubuntu/authd/internal/userutils"
+)
+
+//go:generate go build -o testhelpers/gpasswd ./testhelpers/gpasswd.go
```
Comment (3v1n0) [inline internal/userutils/userutils_test.go:12]: Better to build tools at testing phase, as generate is mostly to generate sources, and if not we should maybe add tags

File: internal/userutils/testhelpers/gpasswd.go [hunk 8]
```diff
@@ -0,0 +1,56 @@
...
+	if groupFile == "" {
+		log.Fatalf("Error: GROUP_FILE environment variable is not set.")
+	}
+	log.Printf("GROUP_FILE: %s", groupFile)
+
+	if filepath.Base(groupFile) != "group" {
+		log.Fatalf("Error: The group file must be named 'group'.")
+	}
+
+	bwrapPath, err := exec.LookPath("bwrap")
```
Comment (3v1n0) [inline internal/userutils/testhelpers/gpasswd.go:32]: So... This is nice, but... Maybe even too nice for our test environments.

In particular:
 - It doesn't work in sbuild / schroot (`bwrap: No permissions to create new namespace, likely because the kernel does not allow non-privileged user namespaces. See <https://deb.li/bubblewrap> or <file:///usr/share/doc/bubblewrap/README.Debian.gz`)
 - It doesn't work in an lxd container (`bwrap: Failed to make / slave: Permission denied`)

So given that we rely on 1st for packages building (and so does launchpad) and the latter as development tool (I personally mostly only develop authd in a container), this test should be likely skipped if the tool isn't supported.

But the fact that it wouldn't run in various places, makes me thinking is probably better to try other solutions (classic preloading? :joy:)

Comment (3v1n0) [reply internal/userutils/testhelpers/gpasswd.go:32]: It's an option, but it also implies that they will not run in packages building and that was something that we didn't want in the past (I know @didrocks wants consistency here), but it's also true that we don't do it for other 

BTW `systemd-detect-virt` or one of these env variables are your friends:

```
SCHROOT_ALIAS_NAME=unstable
SCHROOT_CHROOT_NAME=unstable
SCHROOT_COMMAND=/usr/bin/zsh
SCHROOT_GID=1000
SCHROOT_GROUP=marco
SCHROOT_SESSION_ID=unstable-844cf711-db53-4a31-bfde-60a92d32d30c
SCHROOT_UID=1000
SCHROOT_USER=marco
````
So likely `SCHROOT_SESSION_ID`

Comment (3v1n0) [reply internal/userutils/testhelpers/gpasswd.go:32]: Ah related to it, I forgot that in any case you should add a `bubblewrap <!nocheck>` build-dependency in `debian/control` too

Comment (3v1n0) [reply internal/userutils/testhelpers/gpasswd.go:32]: ... and `qa.yaml`, but I'm not sure bwrap would run there either...

File: .github/workflows/qa.yaml [hunk 9]
```diff
@@ -24,6 +24,7 @@ env:
     libpwquality-dev
 
   test_apt_deps: >-
+    bwrap
```
Comment (3v1n0) [inline .github/workflows/qa.yaml:27]: package is bubblewrap IIRC

File: internal/userutils/userutils.go (hunk 6 above)
Comment (adombeck) [reply internal/userutils/userutils.go]: Now that we have a working test which checks that the locking works and gpasswd refuses to modify the file, isn't that good enough? What could we possible gain from using `lckpwdf` as well?

File: internal/userutils/testhelpers/gpasswd.go (hunk 8 above)
Comment (adombeck) [reply internal/userutils/testhelpers/gpasswd.go:32]: I'm now running `bwrap` via `sudo` if unprivileged user namespaces are not available. That works in the CI at least.

Comment (adombeck) [reply internal/userutils/testhelpers/gpasswd.go:32]: And if that's also not possible, then the test is skipped.

**Comment by adombeck** [comment]
Tests are finally passing in the CI. Time for another round of review.

File: internal/userutils/testhelpers/gpasswd.go
Comment (3v1n0) [inline internal/userutils/testhelpers/gpasswd.go:1]: Yeah, always better to protect these binary

File: internal/userutils/userutils.go [hunk 10]
```diff
@@ -0,0 +1,40 @@
...
+	if _, err := lockFile.WriteString(fmt.Sprintf("%d", os.Getpid())); err != nil {
+		return fmt.Errorf("failed to write PID to lock file: %w", err)
+	}
+
+	return nil
+}
+
+// UnlockGroupFile removes the lock file created by LockGroupFile.
+func UnlockGroupFile() error {
+	if err := os.Remove(GroupFile + ".lock"); err != nil {
```
Comment (3v1n0) [inline internal/userutils/userutils.go:36]: I'd also even a local mutex, so that we have the locking in place also at logical level in go, and there's lo risk that two go-routine could misbehave here.

File: internal/userutils/userutils_test.go [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+	tempDir := t.TempDir()
+	gpasswdHelperPath = tempDir + "/gpasswd"
+	//nolint:gosec // G204 It's fine to pass a variable to exec.Command here
+	cmd := exec.Command("go", "build",
+		"-o", gpasswdHelperPath,
+		"-tags", "userutils_testhelpers",
+		"./testhelpers/gpasswd.go")
+	cmd.Stdout = os.Stdout
+	cmd.Stderr = os.Stderr
+	err := cmd.Run()
```
Comment (3v1n0) [inline internal/userutils/userutils_test.go:43]: Why not using `CombinedOutput()` and then writing the output to the test log and in other places?

So that we respect `-test.v` option and it's properly shown in CI logs. Or in failure only.

If you want see it in real time you could use `testutils.IsVerbose()`, but I don't feel it's needed.

File: internal/userutils/testhelpers/gpasswd.go [hunk 12]
```diff
@@ -0,0 +1,62 @@
+// This is a small wrapper around the gpasswd command, which allows to run
+// gpasswd on a group file that's not at /etc/group. It does this by:
+//   - Reading the path to the group file from the GROUP_FILE environment variable.
+//   - Running the gpasswd command in a bubblewrap sandbox with the group file
+//     bind-mounted to /etc/group.
+//
+// The group file must be named "group".
+
+//go:build userutils_testhelpers
```
Comment (3v1n0) [inline internal/userutils/testhelpers/gpasswd.go:9]: Ah, also add the comment to avoid Tiobe analysis. I don't think we care adding coverage to this one, so we can likely skip it. Or just see how we use `testutils.CoverDirForTests()` and `AppendCovEnv` for other integration tests, if we want to keep high the coverage percentage :)

File: internal/userutils/userutils_test.go [hunk 13]
```diff
@@ -0,0 +1,126 @@
...
+
+func TestLockAndUnlockGroupFile(t *testing.T) {
+	// This test requires either root privileges, unprivileged user namespaces, or being
+	// able to run sudo without user interaction.
+	if os.Geteuid() == 0 {
+		log.Info(context.Background(), "Running as EUID 0")
+	} else if canUseUnprivilegedUserNamespaces() {
+		log.Info(context.Background(), "Can use unprivileged user namespaces")
+	} else if canUseSudoNonInteractively() {
+		log.Info(context.Background(), "Can use sudo non-interactively")
```
Comment (3v1n0) [inline internal/userutils/userutils_test.go:27]: Use t.log here instead, we don't want to bother if -v  isn't used as the result should be enough.

File: internal/userutils/userutils_test.go [hunk 14]
```diff
@@ -0,0 +1,126 @@
...
+	}, args...)
+
+	if useSudo {
+		args = append([]string{"sudo"}, args...)
+	}
+
+	log.Infof(context.Background(), "Running command: %s", strings.Join(args, " "))
+	//nolint:gosec // G204 It's fine to pass variables to exec.Command here
+	cmd := exec.Command(args[0], args[1:]...)
+	return cmd.CombinedOutput()
```
Comment (3v1n0) [inline internal/userutils/userutils_test.go:125]: I'd return a `strings.TrimSpace()` here so that we don't have to call `strings()` everywhere in the test

File: internal/userutils/userutils_test.go [hunk 15]
```diff
@@ -0,0 +1,126 @@
...
+	output, err = runGPasswd("--delete", "root", "testgroup")
+	require.NoError(t, err, string(output))
+}
+
+func canUseUnprivilegedUserNamespaces() bool {
+	cmd := exec.Command("bwrap", "--ro-bind", "/", "/", "--unshare-user", "--uid", "0", "/bin/true")
+	cmd.Stdout = os.Stdout
+	cmd.Stderr = os.Stderr
+	if err := cmd.Run(); err != nil {
+		log.Warningf(context.Background(), "Can't use unprivileged user namespaces: %v", err)
```
Comment (3v1n0) [inline internal/userutils/userutils_test.go:93]: ditto

File: internal/userutils/userutils_test.go [hunk 16]
```diff
@@ -0,0 +1,126 @@
...
+
+	return true
+}
+
+func canUseSudoNonInteractively() bool {
+	cmd := exec.Command("sudo", "-Nnv")
+	cmd.Stdout = os.Stdout
+	cmd.Stderr = os.Stderr
+	if err := cmd.Run(); err != nil {
+		log.Warningf(context.Background(), "Can't use sudo non-interactively: %v", err)
```
Comment (3v1n0) [inline internal/userutils/userutils_test.go:105]: ditto, marking these functions as `t.Helper()`

File: internal/userutils/userutils_test.go [hunk 17]
```diff
@@ -0,0 +1,126 @@
...
+		return false
+	}
+
+	return true
+}
+
+func runGPasswd(args ...string) ([]byte, error) {
+	args = append([]string{
+		"env", "GROUP_FILE=" + groupFile,
```
Comment (3v1n0) [inline internal/userutils/userutils_test.go:114]:
```suggestion
		"env", "LANG=C", "GROUP_FILE=" + groupFile,
```

Since we're parsing the output, so we need to make sure gettext isn't affecting us

File: internal/userutils/userutils.go [hunk 18]
```diff
@@ -0,0 +1,40 @@
...
+package userutils
+
+import (
+	"errors"
+	"fmt"
+	"os"
+)
+
+// GroupFile is the path to the group file. It is exported for testing purposes.
+var GroupFile = "/etc/group"
```
Comment (3v1n0) [inline internal/userutils/userutils.go:11]: just keep it unexported and add an `export_test.go` file with it.

Comment (3v1n0) [reply internal/userutils/userutils.go:11]: Actually... No, keep it exported but change the comment and use it also in 

```diff
diff --git a/internal/users/localentries/localgroups.go b/internal/users/localentries/localgroups.go
index 8c3b5b86..1740914a 100644
--- a/internal/users/localentries/localgroups.go
+++ b/internal/users/localentries/localgroups.go
@@ -13,12 +13,13 @@ import (
 	"sync"
 
 	"github.com/ubuntu/authd/internal/sliceutils"
+	"github.com/ubuntu/authd/internal/userutils"
 	"github.com/ubuntu/authd/log"
 	"github.com/ubuntu/decorate"
 )
 
 var defaultOptions = options{
-	groupPath:    "/etc/group",
+	groupPath:    userutils.GroupFile,
 	gpasswdCmd:   []string{"gpasswd"},
 	getUsersFunc: getPasswdUsernames,
 }
```

Comment (3v1n0) [reply internal/userutils/userutils.go:11]: While `internal/users/db/migration.go` should probably not have to import it instead but `renameUsersInGroupFile` should return an error mentioning it in case, no?

File: internal/userutils/userutils_test.go [hunk 19]
```diff
@@ -0,0 +1,126 @@
...
+
+	// Lock the group file
+	err = userutils.LockGroupFile()
+	require.NoError(t, err)
+
+	// Try using gpasswd to modify the group file. This should fail, because
+	// the group file is locked.
+	output, err = runGPasswd("--delete", "root", "testgroup")
+	require.Error(t, err, string(output))
+	require.Contains(t, string(output), "gpasswd: cannot lock /etc/group")
```
Comment (3v1n0) [inline internal/userutils/userutils_test.go:72]:
```suggestion
	require.Contains(t, string(output), "gpasswd: cannot lock %q", GroupFile)
```

File: internal/userutils/userutils.go [hunk 20]
```diff
@@ -0,0 +1,40 @@
...
+
+// LockGroupFile creates a lock file at /etc/group.lock, the same location
+// used by tools like gpasswd and groupmod to prevent concurrent modifications
+// to the /etc/group file.
+// The lock file contains the PID of the process that created it.
+func LockGroupFile() (err error) {
+	lockFile, err := os.OpenFile(GroupFile+".lock", os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
```
Comment (3v1n0) [inline internal/userutils/userutils.go:18]: I see the [original implementation](https://salsa.debian.org/debian/libuser/blob/7abf20577065bf0d48703ece1c0a1b18a4bc2e67/modules/files.c#L291-L291) is doing things a bit differently:
 - Creates a temporary file
 - Tries to hard-link it

gpasswd does something similar but using a `/etc/group.pid` as source file, but that seems to me even unsafer.

Maybe because it can be a faster operation... However what we do here with `os.EXCL` and with sync, I think it should be enough too.

The only thing is that if an app is fast enough to check if the file exists, then it may return the `Invalid contents of lock `%s'` error instead of telling us what it is, but it shouldn't matter much.

```suggestion
	lockFile, err := os.OpenFile(GroupFile+".lock", os.O_CREATE|os.O_EXCL|os.O_WRONLY|os.O_SYNC, 0600)
```

**Comment by 3v1n0** [comment]
Oh ignore my comments as I have drafted and others are in my plans, some followup changes, so I can handle various comments there.

File: internal/userutils/userutils_test.go (hunk 17 above)
Comment (adombeck) [reply internal/userutils/userutils_test.go:114]: great catch!

File: internal/userutils/userutils.go (hunk 10 above)
Comment (3v1n0) [reply internal/userutils/userutils.go:36]: Not a problem for this branch, in case I will handle in a future one.

File: internal/userutils/userutils.go (hunk 6 above)
Comment (3v1n0) [reply internal/userutils/userutils.go]: Leaving it here for the records: `lckpwdf` is used everywhere while systemd ignores the per files-databases.

https://github.com/systemd/systemd/blob/bf478dcffbc3c568fb3a3c8e8b93b3e7b66f4228/src/basic/user-util.c#L670-L675

And other than that the behavior is different, so let's just go the libc-way.

File: internal/userutils/testhelpers/gpasswd.go (hunk 8 above)
Comment (3v1n0) [reply internal/userutils/testhelpers/gpasswd.go:35]: Most of environments work now, also for `lxd` [enabling nesting](https://ubuntu.com/blog/nested-containers-in-lxd) is enough to get this working.

File: internal/fileutils/fileutils.go [hunk 21]
```diff
@@ -39,3 +39,32 @@ func Touch(path string) error {
 	}
 	return file.Close()
 }
+
+// Copy copies a file from a source to a destination path, preserving the file mode.
+func Copy(srcPath, destPath string) error {
```
Comment (adombeck) [inline internal/fileutils/fileutils.go:44]:
```suggestion
func CopyFile(srcPath, destPath string) error {
```

File: internal/fileutils/fileutils.go [hunk 22]
```diff
@@ -39,3 +39,32 @@ func Touch(path string) error {
...
+	src, err := os.Open(srcPath)
+	if err != nil {
+		return err
+	}
+	defer src.Close()
+
+	dst, err := os.Create(destPath)
```
Comment (adombeck) [inline internal/fileutils/fileutils.go:51]: We can move the `os.Stat(srcPath)` here and then use `os.OpenFile(dst, O_RDWR|O_CREATE|O_TRUNC, info.Mode())` to create the file instead of using `Chmod` (so one syscall less).

File: internal/testutils/testhelpers/bubblewrap-runner/bubblewrap-runner.go [hunk 23]
```diff
@@ -0,0 +1,93 @@
+// This is a small wrapper around the gpasswd command, which allows to run
+// gpasswd on a group file that's not at /etc/group. It does this by:
+//   - Reading the path to the group file from the GROUP_FILE environment variable.
+//   - Running the gpasswd command in a bubblewrap sandbox with the group file
+//     bind-mounted to /etc/group.
```
Comment (adombeck) [inline internal/testutils/testhelpers/bubblewrap-runner/bubblewrap-runner.go:5]: Looks like this file is not gpasswd-specific anymore, but the comment still mentions gpasswd

File: internal/testutils/testhelpers/bubblewrap-runner/bubblewrap-runner.go [hunk 24]
```diff
@@ -0,0 +1,93 @@
...
+
+	if e := os.Getenv("GOCOVERDIR"); e != "" {
+		bwrapArgs = append(bwrapArgs, "--bind", e, e)
+	}
+
+	if os.Geteuid() != 0 {
+		bwrapArgs = append(bwrapArgs, "--unshare-user", "--uid", "0")
+	}
+
+	// Add the gpasswd command arguments
```
Comment (adombeck) [inline internal/testutils/testhelpers/bubblewrap-runner/bubblewrap-runner.go:83]:
```suggestion
	// Add the command arguments
```

or just remove the comment, because it doesn't really explain anything that's not obvious

File: internal/fileutils/fileutils.go (hunk 22 above)
Comment (3v1n0) [reply internal/fileutils/fileutils.go:51]: Neat!

File: internal/testutils/testhelpers/bubblewrap-runner/bubblewrap-runner.go (hunk 23 above)
Comment (3v1n0) [reply internal/testutils/testhelpers/bubblewrap-runner/bubblewrap-runner.go:5]: Yeah, actually we can even drop the whole file as separate executable to keep things easier.

File: internal/testutils/bubblewrap.go [hunk 25]
```diff
@@ -0,0 +1,182 @@
...
+var (
+	bubbleWrapSupportsUnprivilegedNamespacesOnce sync.Once
+	bubbleWrapSupportsUnprivilegedNamespaces     bool
+
+	bubbleWrapNeedsSudoOnce sync.Once
+	bubbleWrapNeedsSudo     bool
+)
+
+// CanRunBubbleWrapTest checks whether we can run tests running in bubblewrap or
+// sip the tests otherwise.
```
Comment (adombeck) [inline internal/testutils/bubblewrap.go:24]:
```suggestion
// skip the tests otherwise.
```

File: internal/testutils/bubblewrap.go [hunk 26]
```diff
@@ -0,0 +1,182 @@
...
+func CanRunBubbleWrapTest(t *testing.T) {
```
Comment (adombeck) [inline internal/testutils/bubblewrap.go:25]: `CanRunBubbleWrapTest` sounds like it should return a bool. I find this more descriptive and idiomatic:

```suggestion
func SkipIfCannotRunBubbleWrap(t *testing.T) {
```

File: internal/testutils/bubblewrap.go (hunk 25 above)
Comment (3v1n0) [reply internal/testutils/bubblewrap.go:24]: Yah thanks for noticing, I had already a fixup with it that apparently I didn't push...

File: internal/testutils/bubblewrap.go [hunk 27]
```diff
@@ -0,0 +1,182 @@
...
+		envArgs = append(envArgs, e)
+	}
+	envArgs = append(envArgs, env...)
+
+	etcDir := filepath.Join(testDataPath, "etc")
+	var etcPerms os.FileMode = 0700
+	if withSudo {
+		// If running in sudo we may want to give the folder more permissions
+		// not to lock out the caller.
+		etcPerms = 0777
```
Comment (adombeck) [inline internal/testutils/bubblewrap.go:89]: Since `/etc` has permissions 0755 and is also owned by root, there should be no need to make the `/etc` in the sandbox writable by non-root users, right?

```suggestion
		etcPerms = 0755
```

File: internal/userutils/userutils.go [hunk 28]
```diff
@@ -0,0 +1,73 @@
...
+
+	overrideLocked atomic.Bool
+)
+
+var (
+	// ErrLock is the error when locking the database fails.
+	ErrLock = errors.New("failed to lock the shadow password database")
+
+	// ErrUnlock is the error when unlocking the database fails.
+	ErrUnlock = errors.New("failed to lock the shadow password database")
```
Comment (adombeck) [inline internal/userutils/userutils.go:23]:
```suggestion
	ErrUnlock = errors.New("failed to unlock the shadow password database")
```

File: internal/testutils/bubblewrap.go (hunk 27 above)
Comment (3v1n0) [reply internal/testutils/bubblewrap.go:89]: Yeah, probably we can even avoid it now, but the problem we had on CI was with removal of the coverage artifacts.
However this happened when it was a subprocess, while I feel now it's not needed anymore so let me try to drop it completely.

File: internal/users/db/migration.go [hunk 29]
```diff
@@ -0,0 +1,316 @@
...
+
+		if oldBackup != "" {
+			// Backup of current group file failed, let's restore the old backup.
+			_ = os.Rename(oldBackup, backupPath)
+		}
+		backupDone = false
+	}
+
+	//nolint:gosec // G306 /etc/group should indeed have 0644 permissions
+	if err := os.WriteFile(groupFile, []byte(strings.Join(newLines, "\n")), 0644); err != nil {
```
Comment (adombeck) [inline internal/users/db/migration.go:302]: Since reading the group file does not require a lock, we should ensure that any updates of the group file are done atomically, i.e. by writing to a temporary file in the same directory first and then renaming that file to replace the original.

That's also what gpasswd does, see https://salsa.debian.org/debian/shadow/blob/4e64c42f1eb9a7c5f238e4b84965551c3976c144/lib/commonio.c#L955-L994.

File: internal/users/db/migration.go [hunk 30]
```diff
@@ -0,0 +1,316 @@
...
+		retErr := fmt.Errorf("error writing %s: %w", groupFile, err)
+		if !backupDone {
+			return retErr
+		}
+
+		if err := os.Rename(backupPath, groupFile); err != nil {
+			log.Errorf(context.Background(), "Failed to restore the backup for the group file: %v", err)
+		}
```
Comment (adombeck) [inline internal/users/db/migration.go:310]: We can omit this when we rename a temporary file. I also don't see gpasswd ever restoring or deleting the backup file it creates, AFAICT it just keeps it around as `/etc/group-`.

File: internal/users/db/migration.go (hunk 29 above)
Comment (adombeck) [reply internal/users/db/migration.go:302]: We should also make sure to resolve symlinks in the destination, similar to https://salsa.debian.org/debian/shadow/blob/4e64c42f1eb9a7c5f238e4b84965551c3976c144/lib/commonio.c#L69-L88.

File: internal/users/db/migration.go [hunk 31]
```diff
@@ -266,6 +266,9 @@ func renameUsersInGroupFile(oldNames, newNames []string) error {
 		newLines = append(newLines, strings.Join(fields, ":"))
 	}
 
+	// Add final new line to the group file.
+	newLines = append(newLines, "")
```
Comment (adombeck) [inline internal/users/db/migration.go:270]: good catch!

File: internal/testutils/bubblewrap.go [hunk 32]
```diff
@@ -48,19 +48,27 @@ func SkipIfCannotRunBubbleWrap(t *testing.T) {
 	t.Skip("Skipping test: requires root privileges or unprivileged user namespaces")
 }
 
+// RunInBubbleWrapWithEnv runs the passed commands in bubble wrap sandbox with env variables.
```
Comment (adombeck) [inline internal/testutils/bubblewrap.go:51]: In commit message of b419d537cb1c3b71350aa996337d214a544ae0ed:

```diff
If another process is locking the shadow password database authd will
-hang until the calling process will not be done with it.
+hang until the calling process will be done with it.
```

Comment (adombeck) [inline internal/testutils/bubblewrap.go:51]: I can't follow the reasoning in the commit message of https://github.com/ubuntu/authd/commit/b419d537cb1c3b71350aa996337d214a544ae0ed:

```
If another process is locking the shadow password database authd will
hang until the calling process will not be done with it.

So ensure this is the case in tests. However in order to verify this we
need to ensure that the locking process is not the same one already
having the lock, as in such case libc is nice enough to just return
early with an error.
```

Why do you want `lckpwdf` to actually block in tests? What are we testing with that (beside the behavior of `lckpwdf`, which is not our code and we shouldn't have to test)?

File: internal/userutils/userutils.go [hunk 33]
```diff
@@ -3,38 +3,71 @@ package userutils
...
+)
+
+// WriteLockShadowPassword locks for writing the shadow password database by
+// using the standard libc lckpwdf() function.
+// While the database is locked read operations can happen, but no other process
+// is allowed to write.
+// Note that this call will block all the other processes trying to access the
+// database in write mode, while it will return an error if called while the
+// lock is already hold by this process.
+func WriteLockShadowPassword() error {
```
Comment (adombeck) [inline internal/userutils/userutils.go:33]: While the man page of `lckpwdf` states that it is for protecting the shadow password database, it's clearly used for more than that, i.e. protecting `/etc/passwd`, `/etc/shadow`, `/etc/group` and `/etc/gshadow`. So IMO we should not pretend that it is only for locking the shadow password database, and also remove "Shadow" from the function names.

The corresponding systemd function is named `take_etc_passwd_lock`. That makes sense as it seems that systemd only ever uses it to protect `/etc/passwd`. We currently only use it to protect `/etc/group`, so I think it would be sensible to name it `LockGroupFile`.

File: internal/userutils/userutils_test.go [hunk 34]
```diff
@@ -0,0 +1,135 @@
...
+	testsListStr := strings.TrimSpace(string(testsList))
+	require.NotEmpty(t, testsListStr, "Setup: test not found", testsListStr)
+
+	lockerBinary := compileLockerBinary(t)
+
+	for _, name := range strings.Split(testsListStr, "\n") {
+		t.Run(name, func(t *testing.T) {
+			t.Parallel()
+
+			testEnv := []string{}
```
Comment (adombeck) [inline internal/userutils/userutils_test.go:39]: nitpick

```suggestion
			var testEnv []string
```

File: internal/users/db/migration.go (hunk 30 above)
Comment (adombeck) [reply internal/users/db/migration.go:310]: > AFAICT it just keeps it around as `/etc/group-`

I suspect that's done so that the user can manually restore the backup in case `gpasswd` was called accidentally. I don't think we need that, because the changes done by authd are done without user interaction. So IMO we don't need to create a backup file at all.

File: internal/userutils/userutils_bwrap_test.go [hunk 35]
```diff
@@ -85,6 +85,26 @@ testgroup:x:1001:testuser`
...
+
+	err := userutils.LockGroupFile()
+	require.NoError(t, err, "Locking once it is allowed")
+
+	err = userutils.LockGroupFile()
+	require.Error(t, err, "Locking again should not be allowed")
+
+	err = userutils.UnlockGroupFile()
+	require.NoError(t, err, "Unlocking should be allowed")
+}
```
Comment (adombeck) [inline internal/userutils/userutils_bwrap_test.go]: This is already tested in `TestLockAndUnlockGroupFile`: https://github.com/ubuntu/authd/blob/92b0d73c99fad6cd7f4f1bb76a41ad356d573858/internal/userutils/userutils_bwrap_test.go#L44-L47

File: internal/testutils/bubblewrap.go [hunk 36]
```diff
@@ -0,0 +1,152 @@
+package testutils
```
Comment (adombeck) [inline internal/testutils/bubblewrap.go:1]: I had some trouble understanding why b327f0b6abcb6527d685a014250ffddae5b9a1e2 was necessary. At first it looked like it just adds quite a lot of complexity for which there is no need. I think I now understand that the reason is that we also need to call `lckpwdf` in an environment which allows it to write to `/etc`. Can you please update the commit message to explain that?

File: internal/users/db/migration.go (hunk 30 above)
Comment (3v1n0) [reply internal/users/db/migration.go:310]: Well, I feel backups are always better to exist than the other way around... Since the code is now there (without adding much complexity) and tested (and won't cause troubles in case of backup failures), IMHO is still better to keep a backup (named even differently if you want) than just overwrite.

And this is common also for non interactive tools such as dpkg (that backups modified configuration files all the times).

So, in case there are situations we didn't consider that the migration may break we still have a safety mechanism.

File: internal/testutils/bubblewrap.go (hunk 32 above)
Comment (3v1n0) [reply internal/testutils/bubblewrap.go:51]: Ah, italianism! :)

File: internal/testutils/bubblewrap.go (hunk 27 above)
Comment (3v1n0) [reply internal/testutils/bubblewrap.go]: Ok, it works fine in CI too, so we can drop it now... This was needed when the directory was created by the wrapper script, but now it's handled all by the caller, so that's not needed.

File: internal/testutils/bubblewrap.go (hunk 32 above)
Comment (3v1n0) [reply internal/testutils/bubblewrap.go:51]: I want to ensure that our locking system works in both ways:
 - If called by a process (`testlocker`) then the other one is stuck
 - If called again by ourself, we return early with a failure

While we're currently just a very simpler wrapper, I want to ensure that our wrapper works as expected in both sides, ensuring that if another local-account database tool is acting, authd behaves - waiting - as expected. And the test is exaggerating the case, of course.

Now, while this was kinda implicit in the usage of `lckpwdf`, I wouldn't give that as granted when cgo (and go runtime) is involved, given that stuff like alarms may not behave in the same way (in fact - for example - they don't as we don't have the 15s max wait when used from go side¹).

---

¹ Since I did notice differences (thanks to the test), I also wanted to include here this further change in fact:

```diff
diff --git a/internal/userutils/userutils.go b/internal/userutils/userutils.go
index c1054c2f..d509b798 100644
--- a/internal/userutils/userutils.go
+++ b/internal/userutils/userutils.go
@@ -4,6 +4,7 @@ package userutils
 import (
 	"errors"
 	"sync/atomic"
+	"time"
 
 	"github.com/ubuntu/authd/internal/testsdetection"
 )
@@ -31,7 +32,21 @@ var (
 // database in write mode, while it will return an error if called while the
 // lock is already hold by this process.
 func WriteLockShadowPassword() error {
-	return writeLockShadowPasswordImpl()
+	done := make(chan error)
+	go func() {
+		done <- writeLockShadowPasswordImpl()
+	}()
+
+	select {
+	// lckpwdf when called from gco doesn't behave exactly the same, likely
+	// because alarms are handled by go runtime, so do it manually here by
+	// failing if "lock not obtained within 15 seconds" as per lckpwdf.3.
+	// Keep this in sync with what lckpwdf does.
+	case <-time.After(15 * time.Second):
+		return ErrLock
+	case err := <-done:
+		return err
+	}
 }
 
 // WriteUnlockShadowPassword unlocks for writing the shadow password database by
```

But I thought it was better to do this (and the related test) in the upcoming branch.

File: internal/userutils/userutils.go (hunk 33 above)
Comment (3v1n0) [reply internal/userutils/userutils.go:33]: We are currently using it for locking group file, but we will need to just lock everything while acting on users and groups, so I'd rather use a "generic name" now and avoid the refactor very soon; and indeed as you guessed I was using that name since it's what the manual refers.

Now, something like `WriteLockLocalAccountsDatabases`? It's very verbose... But...

Or maybe.... Just move all this into the namespace we already have for this stuff (`localentries`, in `internal/users`)  and just use `localentries.WriteLock`, `localentries.WriteUnlock`, as it should be quite self-explainatory

File: internal/userutils/userutils_bwrap_test.go (hunk 35 above)
Comment (3v1n0) [reply internal/userutils/userutils_bwrap_test.go]: Yeah, I will remove it from that one since that's a too long test doing too many checks already, while this is more concise.

File: internal/testutils/bubblewrap.go (hunk 36 above)
Comment (3v1n0) [reply internal/testutils/bubblewrap.go:1]: > I think I now understand that the reason is that we also need to call lckpwdf in an environment which allows it to write to /etc

Yes, plus there are various other reasons why that has happened:
 - Be able to easily add and run multiple tests inside the bwrap environment
 - Have a generic way to test inside a such environment (that will be useful in future for other integration tests)
 - Run all these tests in parallel

Added in the commit

File: internal/users/db/migration.go (hunk 29 above)
Comment (3v1n0) [reply internal/users/db/migration.go:302]: Oh, I wanted to mention that too...

So I've also added a commit doing it.

> We should also make sure to resolve symlinks in the destination, similar to https://salsa.debian.org/debian/shadow/blob/4e64c42f1eb9a7c5f238e4b84965551c3976c144/lib/commonio.c#L69-L88.

This is the normal go behavior, in fact Open does follow symlinks, unless `syscall.O_NOFOLLOW` is used.
Added a test to ensure that though

Comment (adombeck) [reply internal/users/db/migration.go]: > This is the normal go behavior, in fact Open does follow symlinks, unless syscall.O_NOFOLLOW is used.

Yes, `os.Open` does follow symlinks, same as `open(2)` from libc. However, `os.Rename` does not, same `rename(2)`, and that's what we're using here to replace the group file.

> Added a test to ensure that though

It seems like the test is testing the wrong thing: It checks the content of `groupsFilePath` when it should check the content of `realGroupsPath`. When fixing the test with

```diff
diff --git a/internal/users/db/db_test.go b/internal/users/db/db_test.go
index fd512e87..93b47410 100644
--- a/internal/users/db/db_test.go
+++ b/internal/users/db/db_test.go
@@ -192,7 +192,7 @@ func TestMigrationToLowercaseUserAndGroupNamesWithSymlinkedGroupFile(t *testing.
        golden.CheckOrUpdate(t, dbContent, golden.WithPath("db"))
 
        // Check the content of the user group file
-       userGroupContent, err := os.ReadFile(groupsFilePath)
+       userGroupContent, err := os.ReadFile(realGroupsPath)
        require.NoError(t, err)
 
        golden.CheckOrUpdate(t, string(userGroupContent), golden.WithPath("groups"))
```

... then the test fails, because the content of the original group file was not migrated to lowercase:

```
        	Error Trace:	/home/adombeck/projects/authd/internal/testutils/golden/golden.go:210
        	            				/home/adombeck/projects/authd/internal/testutils/golden/golden.go:241
        	            				/home/adombeck/projects/authd/internal/testutils/golden/golden.go:79
        	            				/home/adombeck/projects/authd/internal/users/db/db_test.go:198
        	Error:      	Golden file content mismatch
        	            	
        	            	Expected (golden):
        	            	--------------------------------------------------
        	            	Group1:x:11111:user1
        	            	--------------------------------------------------
        	            	
        	            	Actual: 
        	            	--------------------------------------------------
        	            	Group1:x:11111:User1
        	            	--------------------------------------------------
        	            	
        	            	━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        	            	Δ Expected (golden) ⟶   Actual
        	            	━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        	            	
        	            	Group1:x:11111:user1
        	            	Group1:x:11111:User1
        	            	
        	Test:       	TestMigrationToLowercaseUserAndGroupNamesWithSymlinkedGroupFile
        	Messages:   	Golden file: /home/adombeck/projects/authd/internal/users/db/testdata/golden/TestMigrationToLowercaseUserAndGroupNamesWithSymlinkedGroupFile/groups
```

File: internal/testutils/bubblewrap.go (hunk 32 above)
Comment (adombeck) [reply internal/testutils/bubblewrap.go:52]: > in fact - for example - they don't as we don't have the 15s max wait when used from go side

I can't reproduce that. Here is what I tried:

```
go build -o /tmp/testlocker ./internal/userutils/testlocker/testlocker.go
sudo /tmp/testlocker
```

in a second terminal:
```
time sudo /tmp/testlocker
```

The second invocation of `testlocker` fails after 15 seconds.

File: internal/userutils/userutils.go (hunk 33 above)
Comment (adombeck) [reply internal/userutils/userutils.go:33]: > avoid the refactor very soon

why do you expect that we need to write to `/etc/passwd` or `/etc/shadow` very soon? I don't see why we would have to do that. We currently don't touch these at all.

File: internal/testutils/bubblewrap.go (hunk 36 above)
Comment (adombeck) [reply internal/testutils/bubblewrap.go:1]: >  I think I now understand that the reason is that we also need to call lckpwdf in an environment which allows it to write to /etc.

I still don't see that mentioned in the commit message.

File: internal/users/db/migration.go (hunk 30 above)
Comment (adombeck) [reply internal/users/db/migration.go]: I removed the backup functionality because it caused unexpected behavior when `/etc/groups` is a symlink (it renamed the symlink to `/etc/groups-`, causing `/etc/groups` to be modified instead of `/etc/real-groups`).

I don't see any benefit of restoring a backup file now that we're replacing the group file by writing to a temporary file and then renaming that file. If the rename succeeds, we don't need the backup. If the rename fails, the original group file is preserved, so there is no need for a backup.

File: internal/users/db/migration.go (hunk 29 above)
Comment (adombeck) [reply internal/users/db/migration.go]: I fixed the test and implemented symlink resolution before renaming.

File: internal/userutils/userutils.go (hunk 33 above)
Comment (3v1n0) [reply internal/userutils/userutils.go:33]: If I want to use this to test the behavior for local users, it will help...

Now we just use root for this, but root is still a special case that has different pam handling normally.

So I'd rather keep this flexible enough so that we can mock users better with it.

Comment (adombeck) [reply internal/userutils/userutils.go:33]: Still not sure I understand, but it's probably not worth explaining more if you can just show me those tests soon :)

How about `LockPasswdAndGroupFiles`?

File: internal/users/db/db_test.go
Comment (3v1n0) [inline internal/users/db/db_test.go:1]: Thanks, indeed that was my idea too!

File: internal/users/db/migration.go
Comment (3v1n0) [inline internal/users/db/migration.go:1]: I'll add a test also for this case... I know `Lrename` is, but it's nice to check also the whole thing

File: internal/fileutils/fileutils.go [hunk 37]
```diff
@@ -65,3 +67,32 @@ func CopyFile(srcPath, destPath string) error {
...
+	err error
+}
+
+func (e SymlinkResolutionError) Error() string {
+	return fmt.Sprintf("%s: %v", e.msg, e.err)
+}
+
+func (e SymlinkResolutionError) Unwrap() error {
+	return e.err
+}
```
Comment (3v1n0) [inline internal/fileutils/fileutils.go:83]: Do we need this is if using instead:

```go
func (e SymlinkResolutionError) Error() string {
	return fmt.Sprintf("%s: %w", e.msg, e.err)
}
```

File: internal/fileutils/fileutils_test.go [hunk 38]
```diff
@@ -246,3 +247,106 @@ func TestCopyFile(t *testing.T) {
...
+		sourceDoesNotExist     bool
+		destIsFile             bool
+		destIsSymlink          bool
+		destIsDanglingSymlink  bool
+		destIsDir              bool
+		destIsUnreadable       bool
+		destParentDoesNotExist bool
+
+		wantError     bool
+		wantErrorType reflect.Type
```
Comment (3v1n0) [inline internal/fileutils/fileutils_test.go:264]: I wouldn't bother reflect here, but rather, use:

`wantErrorEquals error` and then just use `require.ErrorIs`

File: internal/users/db/migration.go
Comment (3v1n0) [reply internal/users/db/migration.go:1]: So, I've added a test for this, but it but it failed because of https://github.com/ubuntu/authd/pull/723#discussion_r2059013976 and because opening a dangling link would fail in the first place.

So I'm unsure we should really do this or either go with:

```go
content, err := os.ReadFile(groupFile)
	if err != nil {
		fi, lstatErr := os.Lstat(groupFile)
		if lstatErr != nil {
			return fmt.Errorf("error reading %s: %w", groupFile, lstatErr)
		}
		if fi.Mode()&os.ModeSymlink == 0 {
			return fmt.Errorf("error reading %s: %w", groupFile, err)
		}

		// Dangling symlink... We can consider the group as an empty file...
	}
```

Which is still not the best IMHO, I'm adding a commit here just for reference, but we can drop it if we consider a case we don't care to support.

As the point of replacing a dangling symlink IMHO isn't relevant when the group file can be read in the first place, and given that NOTHING should be modifying it meanwhile we've the lock, we can assume that also the destination is not a broken symlink, isn't it?

File: internal/userutils/userutils.go (hunk 33 above)
Comment (3v1n0) [reply internal/userutils/userutils.go:33]: Well, every time we're processing an user request we'll have to lock the local entries, to ensure that nothing else will try to interfere meanwhile, so this about locking everything.

I'd rather move everything to `localentries` and see what you think. Since that namespace is meant to handle local groups and users.

File: internal/testutils/bubblewrap.go (hunk 32 above)
Comment (3v1n0) [reply internal/testutils/bubblewrap.go:52]: Maybe that's a simpler case and other stuff we have don't apply, what I was doing is applying this diff to the tests:

Then run the test with `go test -C internal/userutils -v -run TestUserUtilsInBubbleWrap/TestLockingLockedDatabase"$"`, it will never stop hanging... While it does using the _manual_ go routine wait... So it seems safe to add the max-timeout (maybe to 16 or more seconds), just in case...

File: internal/testutils/bubblewrap.go (hunk 36 above)
Comment (3v1n0) [reply internal/testutils/bubblewrap.go:1]: Oh, ok... I'll add it just before the final rebase.

File: internal/users/db/migration.go [hunk 39]
```diff
@@ -273,7 +274,14 @@ func renameUsersInGroupFile(oldNames, newNames []string) error {
 		return fmt.Errorf("error writing %s: %w", tempPath, err)
 	}
 
-	if err := os.Rename(tempPath, groupFile); err != nil {
+	err = fileutils.Lrename(tempPath, groupFile)
+	var symlinkErr *fileutils.SymlinkResolutionError
+	if errors.As(err, &symlinkErr) {
+		log.Warning(context.Background(), err.Error())
+		// If the symlink resolution fails, we rename the symlink without resolving it.
+		err = os.Rename(tempPath, groupFile)
```
Comment (3v1n0) [inline internal/users/db/migration.go:289]: With current code is quite hard (if not impossible) to reach this since the initial `content, err := os.ReadFile(groupFile)` would not work if the group file points to something that cannot be resolved.

File: internal/testutils/bubblewrap.go (hunk 32 above)
Comment (adombeck) [reply internal/testutils/bubblewrap.go:52]: I can reproduce it with your reproducer.

If we have to handle the timeout ourselves, then it might better we just reimplement the whole `lckpwdf` ourselves, like systemd did. IIUC correctly, it's basically just an `open(path, O_WRONLY|O_CREAT|O_CLOEXEC|O_NOCTTY|O_NOFOLLOW, 0600)` and a `fcntl` call.

File: internal/userutils/userutils.go (hunk 33 above)
Comment (adombeck) [reply internal/userutils/userutils.go]: > every time we're processing an user request we'll have to lock the local entries, to ensure that nothing else will try to interfere meanwhile

Wait what? Why do we have to lock anything on a user request? We only need `lckpwdf` because we're writing to `/etc/groups` directly when migrating to lowercase usernames, which is a one-time operation done during authd startup.

Comment (adombeck) [reply internal/userutils/userutils.go]: I'm also getting the feeling we're spending way too much effort on making this migration absolutely safe, given that it only happens once for each existing authd installation. The chance that something else is writing to `/etc/groups` at the same time seems negligible.

File: internal/users/db/db_test.go
Comment (adombeck) [reply internal/users/db/db_test.go:1]: > but I still think we should keep a backup when we touch a system file. There's always risk we do something unexpected.

Who should restore that backup if something goes wrong? We only replace the original if all went well. If we don't notice that something went wrong, an admin would need to restore the backup if *they* notice that something isn't working correctly. This opens up a can of worms:
* How do we let admins know that this backup exists?
* This might have privacy implications, since we're storing a list of user and group names and their mapping. Do we ever delete it or just keep it around forever?
* Do we want to overwrite the `/etc/group-` which was created by the last *manual* use of `gpasswd`?

File: internal/users/db/migration.go [hunk 40]
```diff
@@ -273,7 +274,14 @@ func renameUsersInGroupFile(oldNames, newNames []string) error {
 		return fmt.Errorf("error writing %s: %w", tempPath, err)
 	}
 
-	if err := os.Rename(tempPath, groupFile); err != nil {
+	err = fileutils.Lrename(tempPath, groupFile)
+	var symlinkErr *fileutils.SymlinkResolutionError
+	if errors.As(err, &symlinkErr) {
```
[the remark this answers is not in the document]
Comment (adombeck) [reply internal/users/db/migration.go]: No. `errors.Is` checks if an error is a specific instance of `error` (e.g. `os.ErrNotExist`), `errors.As` checks if an error is of a specific type of error.

File: internal/fileutils/fileutils.go (hunk 37 above)
Comment (adombeck) [reply internal/fileutils/fileutils.go:83]: `fmt.Sprintf` doesn't have a `%w` specifier, only `fmt.Errorf` does

File: internal/fileutils/fileutils_test.go (hunk 38 above)
Comment (adombeck) [reply internal/fileutils/fileutils_test.go]: that doesn't work when verifying if an error is of a specific error type instead of a specific error instance.

File: internal/users/db/migration.go [hunk 41]
```diff
@@ -273,7 +274,14 @@ func renameUsersInGroupFile(oldNames, newNames []string) error {
 		return fmt.Errorf("error writing %s: %w", tempPath, err)
 	}
 
-	if err := os.Rename(tempPath, groupFile); err != nil {
+	err = fileutils.Lrename(tempPath, groupFile)
+	var symlinkErr *fileutils.SymlinkResolutionError
```
[the remark this answers is not in the document]
Comment (adombeck) [reply internal/users/db/migration.go]: Yes, that should have been `var symlinkErr fileutils.SymlinkResolutionError`

File: internal/users/db/migration.go (hunk 39 above)
Comment (3v1n0) [reply internal/users/db/migration.go:288]: Well if we have te lock it shouldn't, no?

And if it does, then there's a system issue.

File: internal/users/db/db_test.go
Comment (3v1n0) [reply internal/users/db/db_test.go:1]: > Do we want to overwrite the /etc/group- which was created by the last manual use of gpasswd?

Yes, as gpasswd either isn't used only by manual use (also authd itself right now is issued programmatically) to change groups.

And also other tools and UIs do it, being the _standard API_. So imho we should just do the same in a best-effort behavior.

File: internal/fileutils/fileutils_test.go (hunk 38 above)
Comment (3v1n0) [reply internal/fileutils/fileutils_test.go]: Well it does now that I've re-impemented Is, and it's a safer way IMHO, so we use the same logic everywhere.

File: internal/users/db/migration.go (hunk 40 above)
[the remark this answers is not in the document]
Comment (3v1n0) [reply internal/users/db/migration.go]: Sure, but that's how we handled it in many cases in authd, re-implementing `Is` so that the error just is not compared against its content.

File: internal/testutils/bubblewrap.go (hunk 32 above)
Comment (3v1n0) [reply internal/testutils/bubblewrap.go:52]: > If we have to handle the timeout ourselves, then it might be better we just reimplement the whole lckpwdf ourselves, like systemd did. IIUC correctly, it's basically just an open(path, O_WRONLY|O_CREAT|O_CLOEXEC|O_NOCTTY|O_NOFOLLOW, 0600) and a fcntl call.

Yes, [that was my idea too](https://warthogs.atlassian.net/browse/UDENG-6745)... But it wasn't for this branch.

So for this one, are you fine to just use the quicker solution above?

File: internal/users/db/migration.go (hunk 39 above)
Comment (adombeck) [reply internal/users/db/migration.go:288]: I think there's always a system issue if `/etc/groups` becomes a dangling symlink.

Comment (3v1n0) [reply internal/users/db/migration.go:288]: Yeah, indeed... I mean, if we assume that it can happen, then we're broken way earlier than that... So, IMHO or we accept "fixing it", or we can't be bothered and we do nothing special here, as it goes a bit of out of scope of our groups management duties.

File: internal/users/db/migration.go (hunk 40 above)
[the remark this answers is not in the document]
Comment (adombeck) [reply internal/users/db/migration.go]:
```
// Is makes this error insensitive to the internal values.
func (e SymlinkResolutionError) Is(target error) bool {
	return target == SymlinkResolutionError{}
}
```

That doesn't unwrap the `target`, so it returns `false` if `target` wraps a `SymlinkResolutionError`. `errors.As` unwraps the target.

[the remark this answers is not in the document]
Comment (3v1n0) [reply internal/users/db/migration.go]: Ah ok... Well we can still use both, as you wish... Feel free to adapt the commit. For the specific case this is enough though.

[the remark this answers is not in the document]
Comment (adombeck) [reply internal/users/db/migration.go]: > that's how we handled it in many cases in authd

I find two places where we define a custom `Is` function for errors in authd:
* https://github.com/ubuntu/authd/blob/c5cd0eb7c4acf9a3a629be41534e9e0d05724f2d/internal/users/db/db.go#L190-L190
* https://github.com/ubuntu/authd/blob/c5cd0eb7c4acf9a3a629be41534e9e0d05724f2d/internal/users/db/bbolt/db.go#L267-L267

Those also have the issue that they don't unwrap the error.

Using `errors.As` to test if an error is of a specific type is the standard Go way, I don't see why we should do it differently in authd.

[the remark this answers is not in the document]
Comment (3v1n0) [reply internal/users/db/migration.go]: Well IIRC those were introduced by @didrocks and I did follow his guidance in other places I've been using a similar thing.

However I'm fine with `error.As` (although it can be more prone to errors, as we saw here), I'd just not like the way to test it using reflect.

[the remark this answers is not in the document]
Comment (adombeck) [reply internal/users/db/migration.go]: I was wrong, implementing the `Is` method like that does actually work for wrapped errors, because the errors are unwrapped and then their `Is` method is called. I'm still not a huge fan of using `errors.Is(err, fileutils.SymlinkResolutionError{})`, because:
1. that's not how `errors.Is` is meant to be used. Implementing the `Is` method is intended to treat an error as equivalent to an existing error, like `fs.ErrExist` (see https://pkg.go.dev/errors#Is).
2. It's relying on the fact that `target` is the zero value. If you call it the other way around (`errors.Is(fileutils.SymlinkResolutionError{}, err)`) or with a different `SymlinkResolutionError` (`errors.Is(err1, err2)`), it fails, while that works when `errors.Is` is used as intended, with errors like `ErrExist = errors.New("file already exists")`.

However, I also see that `errors.As` is a bit harder to work with and more error prone. So I'm fine with keeping it the way it is. It won't work for custom error types we get from third-party packages though, so we will eventually have to use `errors.As` when we are handling custom error from third-party packages.

File: internal/users/db/db_test.go
Comment (adombeck) [reply internal/users/db/db_test.go:1]: > And also other tools and UIs do it, being the standard API.

That's a good point. I verified that other tools (usermod and groupmod) from the shadow-utils also create this backup file. The shadow-utils are indeed also the standard way to modify users and groups programmatically, so I'm now convinced that it's fine that we closely replicate their behavior, including the creation of the backup file. Can we agree that we don't try to automatically restore that backup? (I'm not sure if we already agreed on that, if so I can't find the thread).

File: internal/users/db/migration.go
Comment (adombeck) [reply internal/users/db/migration.go:1]: Note that a dangling symlink is not the only case in which `Lrename` returns a `SymlinkResolutionError`, it could for example also be a permission denied or a "too many links" error (which is returned when `EvalSymlinks` followed more than 255 links, which is indicator for a symlink loop).

I implemented the behavior to rename the symlink if resolving it fails to closely follow the behavior of the `lrename` function used by gpasswd, which also [just prints any error returned by `realpath(3)` and continues renaming it](https://salsa.debian.org/debian/shadow/blob/4e64c42f1eb9a7c5f238e4b84965551c3976c144/lib/commonio.c#L79-L88).

That said, I'm also fine with just returning the error, because it is a clear indication that something is broken.

File: internal/users/db/migration.go (hunk 39 above)
Comment (adombeck) [reply internal/users/db/migration.go:288]: > or we can't be bothered and we do nothing special here, as it goes a bit of out of scope of our groups management duties

fine by me (see https://github.com/ubuntu/authd/pull/723#discussion_r2063252916)

File: internal/users/db/db_test.go [hunk 42]
```diff
@@ -131,8 +131,8 @@ func TestMigrationToLowercaseUserAndGroupNames(t *testing.T) {
 	t.Cleanup(func() { db.SetGroupFile(origGroupFile) })
 
 	// Make the userutils package to use test locking for the group file
-	userutils.OverrideShadowPasswordLocking()
-	t.Cleanup(userutils.RestoreShadowPasswordLocking)
+	localentries.OverrideLocking()
+	t.Cleanup(localentries.RestoreLocking)
```
Comment (adombeck) [inline internal/users/db/db_test.go:135]: > userutils: Move local database locking into localentries
> 
> localentries contains types for handling local users and groups and
> that's where locking is needed, so use move the locking user utilities
> here instead.

Since we plan to use the locking when we pick a UID/GID for an authd user/group (UDENG-6745), I think the locking fits better into the more generic `userutils` package than the `localentries` package. If you prefer to have it below `internal/users/`, I would also be fine with putting into a separate `internal/users/locking/` package.

Comment (3v1n0) [reply internal/users/db/db_test.go:135]: > Since we plan to use the locking when we pick a UID/GID for an authd user/group (UDENG-6745), I think the locking fits better into the more generic userutils package than the localentries package. If you prefer to have it below internal/users/, I would also be fine with putting into a separate internal/users/locking/ package.

I liked the fact to use the package as the clear statement of what this locks (not only users though), so given it locks the local entries (and potentially other NSS modules acting on them), I thought it was the right spot.

I'm fine to move it to somewhere else too, but maybe `locking` is too generic too, so maybe `internal/users/pwdlocking` or (even not inside `users`)?

File: internal/fileutils/fileutils_test.go [hunk 43]
```diff
@@ -154,3 +153,199 @@ func TestTouch(t *testing.T) {
...
+		sourceDoesNotExist     bool
+		destIsFile             bool
+		destIsSymlink          bool
+		destIsDanglingSymlink  bool
+		destIsDir              bool
+		destIsUnreadable       bool
+		destParentDoesNotExist bool
+
+		wantError      bool
+		wantErrorTyped error
```
[the remark this answers is not in the document]
Comment (3v1n0) [reply internal/fileutils/fileutils_test.go:263]: that's fine, I don't think duplicating the want to be a big deal, but if we want static check a trick is inside doing something:

```diff
diff --git a/internal/fileutils/fileutils_test.go b/internal/fileutils/fileutils_test.go
index d2a69b8d..b23580bd 100644
--- a/internal/fileutils/fileutils_test.go
+++ b/internal/fileutils/fileutils_test.go
@@ -1,6 +1,7 @@
 package fileutils_test
 
 import (
+	"errors"
 	"os"
 	"path/filepath"
 	"testing"
@@ -247,6 +248,8 @@ func TestCopyFile(t *testing.T) {
 	}
 }
 
+var anyErr = errors.New("This is a generic error")
+
 func TestLrename(t *testing.T) {
 	t.Parallel()
 
@@ -259,19 +262,18 @@ func TestLrename(t *testing.T) {
 		destIsUnreadable       bool
 		destParentDoesNotExist bool
 
-		wantError      bool
-		wantErrorTyped error
+		wantError error
 	}{
 		"Successfully_rename_file_if_destination_does_not_exist": {},
 		"Successfully_rename_file_if_destination_is_a_file":      {destIsFile: true},
 		"Successfully_rename_file_if_destination_is_a_symlink":   {destIsSymlink: true},
 		"Successfully_rename_file_if_destination_is_unreadable":  {destIsFile: true, destIsUnreadable: true},
 
-		"Error_when_source_does_not_exist":                       {sourceDoesNotExist: true, wantError: true},
-		"Error_when_destination_is_a_directory":                  {destIsDir: true, wantError: true},
-		"Error_when_destination_parent_directory_does_not_exist": {destParentDoesNotExist: true, wantError: true},
-		"Error_when_destination_is_a_dangling_symlink":           {destIsDanglingSymlink: true, wantErrorTyped: fileutils.SymlinkResolutionError{}},
-		"Error_unwrap_when_destination_is_a_dangling_symlink":    {destIsDanglingSymlink: true, wantErrorTyped: os.ErrNotExist},
+		"Error_when_source_does_not_exist":                       {sourceDoesNotExist: true, wantError: anyErr},
+		"Error_when_destination_is_a_directory":                  {destIsDir: true, wantError: anyErr},
+		"Error_when_destination_parent_directory_does_not_exist": {destParentDoesNotExist: true, wantError: anyErr},
+		"Error_when_destination_is_a_dangling_symlink":           {destIsDanglingSymlink: true, wantError: fileutils.SymlinkResolutionError{}},
+		"Error_unwrap_when_destination_is_a_dangling_symlink":    {destIsDanglingSymlink: true, wantError: os.ErrNotExist},
 	}
 
 	for name, tc := range tests {
@@ -327,12 +329,12 @@ func TestLrename(t *testing.T) {
 			}
 
 			err := fileutils.Lrename(srcPath, destPath)
-			if tc.wantErrorTyped != nil {
-				require.ErrorIs(t, err, tc.wantErrorTyped, "Error should match")
+			if errors.Is(tc.wantError, anyErr) {
+				require.Error(t, err, "Lrename should return an error")
 				return
 			}
-			if tc.wantError {
-				require.Error(t, err, "Lrename should return an error")
+			if tc.wantError != nil {
+				require.ErrorIs(t, err, tc.wantError, "Error should match")
 				return
 			}
 			require.NoError(t, err, "Lrename should not return an error")
```

File: internal/users/db/migration.go
Comment (3v1n0) [reply internal/users/db/migration.go:1]: Ah I see... Well, let's not try to fix the world I'd say... let's just keep it simpler and error out.

File: internal/users/db/db_test.go
Comment (3v1n0) [reply internal/users/db/db_test.go:1]: > Can we agree that we don't try to automatically restore that backup? (I'm not sure if we already agreed on that, if so I can't find the thread).

Indeed, that's fine for me... Don't care much about restoring, I feel it's fine to just do a copy and then whatever it happens, users have still some trace.

Indeed, we may end up overwriting it again, but that's fine.

File: internal/userutils/userutils.go (hunk 33 above)
Comment (3v1n0) [reply internal/userutils/userutils.go]: Let's close this conversation, for the public record the related resources were https://github.com/systemd/systemd/blob/main/docs/UIDS-GIDS.md?plain=1#L224-L233

On the naming side, let's move to https://github.com/ubuntu/authd/pull/723#discussion_r2063310609

File: internal/users/db/db_test.go (hunk 42 above)
Comment (3v1n0) [reply internal/users/db/db_test.go:135]: Ok, moved to `users/locking` but preserved the namespace as `userslocking` so that it's not confused when used outside users namespace (as per @didrocks suggestion too).

File: internal/services/nss/nss.go [hunk 44]
```diff
@@ -40,22 +41,25 @@ func NewService(ctx context.Context, userManager *users.Manager, brokerManager *
 
 // GetPasswdByName returns the passwd entry for the given username.
 func (s Service) GetPasswdByName(ctx context.Context, req *authd.GetPasswdByNameRequest) (*authd.PasswdEntry, error) {
-	if req.GetName() == "" {
+	name := req.GetName()
+	if name == "" {
 		return nil, status.Error(codes.InvalidArgument, "no user name provided")
 	}
```
[the remark this answers is not in the document]
Comment (3v1n0) [reply internal/services/nss/nss.go:48]: Silli AI, this is done by the next `s.userManager.UserByName()` and later by `s.userPreCheck()`!

File: internal/users/db/db_test.go [hunk 45]
```diff
@@ -112,6 +113,291 @@ func TestDatabaseRemovedWhenSchemaCreationFails(t *testing.T) {
...
+	groupsFilePath := filepath.Join(t.TempDir(), "groups")
+	err = os.WriteFile(groupsFilePath, []byte("Group1:x:11111:User1\n"), 0600)
+	require.NoError(t, err, "Setup: could not create group file")
+
+	// Make the db package use the temporary group file
+	origGroupFile := db.GroupFile()
+	db.SetGroupFile(groupsFilePath)
+	t.Cleanup(func() { db.SetGroupFile(origGroupFile) })
+
+	// Make the userutils userslocking to use test locking for the group file
```
[the remark this answers is not in the document]
Comment (adombeck) [reply internal/users/db/db_test.go:133]: This comment exists multiple times, I'm not going to comment on each one

File: internal/users/locking/locking.go [hunk 46]
```diff
@@ -3,6 +3,7 @@ package userslocking
 import (
```
Comment (adombeck) [inline internal/users/locking/locking.go:4]:
```diff
-users/locking: Fail if users lock is not acquired in enough time
+users/locking: Fail if acquiring lock takes too long

libc by default errors out if the lock is not acquired in 15 seconds, we
-replicate the same to ensure that authd won't never hang indefinitely if
+replicate the same to ensure that authd will never hang indefinitely if
-the libc alarm mechanism doesn't work properly (as it may not be handled
+the libc alarm mechanism doesn't work properly (we've seen it not work
as expected when go runtime is involved).

File: internal/users/locking/locking.go [hunk 47]
```diff
@@ -30,7 +31,21 @@ var (
...
 // lock is already hold by this process.
 func WriteLock() error {
-	return writeLockImpl()
+	done := make(chan error)
+	go func() {
+		done <- writeLockImpl()
+	}()
+
+	select {
+	// lckpwdf when called from gco doesn't behave exactly the same, likely
```
Comment (adombeck) [inline internal/users/locking/locking.go:41]: `s/gco/cgo`?

File: internal/users/locking/locking_bwrap_test.go [hunk 48]
```diff
@@ -0,0 +1,358 @@
...
+	go func() {
+		lockerExited <- cmd.Run()
+	}()
+
+	select {
+	case <-time.After(sleepDuration(1 * time.Second)):
+		t.Cleanup(func() { cmd.Process.Kill() })
+		// If we're time-outing: it's fine, it means the test-locker process is running
+	case err := <-lockerExited:
+		require.NoError(t, err, "test locker should have not failed")
```
Comment (adombeck) [inline internal/users/locking/locking_bwrap_test.go:198]:
```suggestion
		require.NoError(t, err, "test locker should not have failed")
```

File: internal/users/locking/locking.go [hunk 49]
```diff
@@ -30,7 +31,21 @@ var (
...
+	// because alarms are handled by go runtime, so do it manually here by
+	// failing if "lock not obtained within 15 seconds" as per lckpwdf.3.
+	// Keep this in sync with what lckpwdf does, adding an extra second.
+	case <-time.After(16 * time.Second):
```
Comment (adombeck) [inline internal/users/locking/locking.go:45]: We might want to use a variable here which can be overridden in the tests, so that the test doesn't take 16 seconds to run.

Comment (didrocks) [reply internal/users/locking/locking.go:45]: If this is only testing in non integration tests to trigger an error, I think this is a good candidate for synctest (https://go.dev/blog/synctest), which is behind a feature flag for 1.24: `GOEXPERIMENT=synctest`. Mind giving it a try?

File: internal/users/locking/locking_bwrap_test.go [hunk 50]
```diff
@@ -0,0 +1,358 @@
...
+
+	t.Log("Waiting for lock")
+	writeLockExited := make(chan error)
+	go func() {
+		writeLockExited <- userslocking.WriteLock()
+	}()
+
+	err := <-writeLockExited
+	t.Log("Done waiting for lock!")
+	require.Error(t, err, userslocking.ErrLock)
```
Comment (adombeck) [inline internal/users/locking/locking_bwrap_test.go:265]:
```suggestion
	require.ErrorIs(t, err, userslocking.ErrLock)
```

File: internal/users/locking/locking_bwrap_test.go [hunk 51]
```diff
@@ -0,0 +1,358 @@
...
+		lockerExited <- cmd.Run()
+	}()
+
+	select {
+	case <-time.After(sleepDuration(1 * time.Second)):
+		t.Cleanup(func() { cmd.Process.Kill() })
+		// If we're time-outing: it's fine, it means the test-locker process is running
+	case err := <-lockerExited:
+		require.NoError(t, err, "test locker should have not failed")
+	}
```
Comment (adombeck) [inline internal/users/locking/locking_bwrap_test.go:255]: Instead of waiting for a second to check if the test locker fails with an unexpected error, we can make `WriteLock` return an `ErrTimeout` error which wraps an `ErrLock`, which we can then check for below:

In `locking.go`:
```
// ErrTimeout is the error when locking the database times out.
ErrTimeout = fmt.Errorf("%w: timeout", ErrLock)
```
```
	case <-time.After(16 * time.Second):
		return ErrTimeout
```

In `TestLockingLockedDatabaseFailsAfterTimeout`:
```
err := <-writeLockExited
t.Log("Done waiting for lock!")
require.ErrorIs(t, err, userslocking.ErrTimeout)
```

File: internal/users/locking/locking.go [hunk 52]
```diff
@@ -0,0 +1,87 @@
+// Package userslocking controls the users NSS and local database locking.
```
Comment (adombeck) [inline internal/users/locking/locking.go:1]:
```suggestion
// Package userslocking implements locking of the local user and group files
// (/etc/passwd, /etc/groups, /etc/shadow, /etc/gshadow) via the libc lckpwdf()
// function.
//
// It is recommended by systemd to hold this lock when picking a new UID/GID to
// avoid races, even if the new user/group is not added to the local user/group
// files. See https://github.com/systemd/systemd/blob/main/docs/UIDS-GIDS.md.
```

File: internal/users/locking/locking.go (hunk 49 above)
Comment (adombeck) [reply internal/users/locking/locking.go:45]: Marco and I discussed this briefly in a HO. It's a nice feature and will be useful in the future, but for this specific package we don't gain much by reducing the runtime of the test, because we have [this other test](https://github.com/ubuntu/authd/blob/7b5640b88916a2c3eddcbb6bccdb0ee94f9883b2/internal/users/locking/locking_bwrap_test.go#L21-L21) which calls `gpasswd` to test that it times out after 15 seconds when we hold the lock. We assume `synctest` won't help us speeding up the sleeps of subprocesses, so running the tests of this package will take ~15 seconds anyway.

**Comment by adombeck** [comment]
@3v1n0 I fixed the history a bit more, tests are now passing on all commits (at least `./internal/users/...` and `./internal/userutils/...`).

**Comment by adombeck** [comment]
This should be good to merge now from my side.

**Comment by adombeck** [comment]
> Comments suppressed due to low confidence (1)
> 
> **internal/fileutils/fileutils.go:86**
> 
>     * [nitpick] The implementation of the Is method for SymlinkResolutionError may not correctly handle error comparisons using the standard errors package conventions. Consider revisiting this implementation to ensure proper error matching.
> 
> 
> ```
> func (e SymlinkResolutionError) Is(target error) bool { return target == SymlinkResolutionError{} }
> ```

I actually agree with the AI on that, but we already had that discussion 😄
